name: Release

on:
  push:
    tags: ['v*']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_ACTOR: ${{ github.actor }}

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Install dev
        run: |
          cp src/app/dev.sh /usr/local/bin/dev
          chmod +x /usr/local/bin/dev
      - name: Push
        run: dev push

  push-images:
    name: Push Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - uses: ./
      - name: Push
        working-directory: images
        run: mdev push
